version: "3.3"
services:
  angular-app:
    build: fe/angular
    volumes: 
      - /etc/letsencrypt:/etc/nginx/certs
    ports: 
      - "80:80" 
      - "443:443" 

  java-app:
    build: be/java
    ports:
      - "8080:8080"    
    
